---
- name: Simple Utility to Clear the SSSD Cache
  hosts: infservers
  tasks:
    - name: stop the sssd service
      ansible.builtin.service:
        name: sssd
        state: stopped

    - name: clear the sssd cache
      ansible.builtin.command: sss_cache -E

    - name: start the sssd service
      ansible.builtin.service:
        name: sssd
        state: started
