---
#  Example patching a process
#
#  Outline:
#    1. 
#
- name: Patch process for RHEL
  hosts: all
  remote_user: ansibleop
  become: true

  tasks:
    - name: Update the Change Order
      ansible.builtin.debug:
        msg: Updating the Change Order to flag host update

    - name: Perform Backup or Snapshot
      ansible.builtin.debug:
        msg: Initiating backup/snapshot

    - name: Disable Monitoring of system
      ansible.builtin.debug:
        msg: Disable alerts for system during the patch process

    - name: Install the latest patches allowed by the Content View
      register: yum_update
      ansible.builtin.yum:
        name: "*"
        state: latest
    # exclude: kernel*

    - name: Restart the system
      when: yum_update.changed
      ansible.builtin.reboot:
        msg: Automated reboot initiated via Ansible Tower automation
        post_reboot_delay: 25
        reboot_timeout: 200

    - name: Install the kpatch RPM
      ansible.builtin.yum:
        name: kpatch
        state: latest

    - name: Start the kpatch.service
      ansible.builtin.service:
        name: kpatch.service
        enabled: true
        state: started

    - name: Enable Monitoring of system
      ansible.builtin.debug:
        msg: Enable monitoring

    - name: Close Change Order
      ansible.builtin.debug:
        msg: Add logs to change order and close it
