---
#  Example patching a RHEL VM Guest
#
#  Outline:
#    1.  Patch RHEL Guest
#    2.  Run the ping module to check if alive
#
- name: Update all available packages with yum
  hosts: all
  remote_user: ansibleop
  become: true

  tasks:
    - name: Install the latest patches allowed by the Content View
      register: yum_update
      ansible.builtin.yum:
        name: "*"
        state: latest

    - name: Invoke Ping module on the host to verify that it is up
      ansible.builtin.ping:
